<a href="https://colab.research.google.com/github/nusujutt1122/python-practice/blob/main/hotel_booking_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION 1

Create a function with one argument formed in DataFrame to check the data type, the number of null values, the percentage of null values and the number of unique values for each column!

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv"
df = pd.read_csv(url)


def column_summary(df):
  summary = pd.DataFrame({
      'data_type': df.dtypes,
      'null_count':df.isnull().sum(),
      'null_percent':df.isnull().sum()/len(df)*100,
      'unique_count':df.nunique(),
  })
  return summary
column_summary(df)

,data_type,null_count,null_percent,unique_count
hotel,object,0,0.000000,2
is_canceled,int64,0,0.000000,2
lead_time,int64,0,0.000000,479
arrival_date_year,int64,0,0.000000,3
arrival_date_month,object,0,0.000000,12
arrival_date_week_number,int64,0,0.000000,53
arrival_date_day_of_month,int64,0,0.000000,31
stays_in_weekend_nights,int64,0,0.000000,17
stays_in_week_nights,int64,0,0.000000,35
adults,int64,0,0.000000,14
children,float64,4,0.003350,5
babies,int64,0,0.000000,5
meal,object,0,0.000000,5
country,object,488,0.408744,177
market_segment,object,0,0.000000,8
distribution_channel,object,0,0.000000,5
is_repeated_guest,int64,0,0.000000,2
previous_cancellations,int64,0,0.000000,15
previous_bookings_not_canceled,int64,0,0.000000,73
reserved_room_type,object,0,0.000000,10
assigned_room_type,object,0,0.000000,12
booking_changes,int64,0,0.000000,21
deposit_type,object,0,0.000000,3
agent,float64,16340,13.686238,333
company,float64,112593,94.306893,352
days_in_waiting_list,int64,0,0.000000,128
customer_type,object,0,0.000000,4
adr,float64,0,0.000000,8879
required_car_parking_spaces,int64,0,0.000000,5
total_of_special_requests,int64,0,0.000000,6
reservation_status,object,0,0.000000,3
reservation_status_date,object,0,0.000000,926

Question 2:

How many visitors are there who cancel the reservation and who don’t? And
from that number draw conclusions about the proportions of each!

In [ ]:
#cancel = 1 , not cancel =0
df['is_canceled'].value_counts()
df['is_canceled'].value_counts(normalize=True) #proportion
print(df['is_canceled'].value_counts())
#37% cancel 44224
#63% not cancel 75166

is_canceled
0    75166
1    44224
Name: count, dtype: int64


Question 3:

a) For “City Hotel”, what is the percentage of canceled reservations?
b) For “Resort Hotel”, what is the percentage of canceled reservations?
c) What type of hotel that has the bigger percentage of canceled
reservations?

In [ ]:

#For “City Hotel”, what is the percentage of canceled reservations?
city = df[df['hotel']=='City Hotel']
print(city['is_canceled'].mean()*100)
#For “Resort Hotel”, what is the percentage of canceled reservations?
resort = df[df['hotel'] == 'Resort Hotel']
print(resort['is_canceled'].mean()*100)
#What type of hotel that has the bigger percentage of canceled reservations?
#city hotel percentage of cancel is more than resort hotel

41.72696331778646
27.763354967548675

In [ ]:
df.groupby('hotel')['is_canceled'].mean()*100

hotel
City Hotel      41.726963
Resort Hotel    27.763355
Name: is_canceled, dtype: float64

Question 4:

Filter data so that it only displays the visitors who don’t cancel the
reservation and save the result in df_checkout variable!

In [ ]:
df['is_canceled']== 0
df_checkout = df[df['is_canceled'] == 0]
df_checkout.shape

(75166, 32)